[package]
name = "cinemarustback"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.6.0"
chrono = "0.4.38"
dotenv = "0.15.0"
env_logger = "0.11.3"
futures-util = "0.3.30"
log = "0.4.21"
mongodb = "2.8.2"
serde = "1.0.203"
serde_json = "1.0.117"
